# Generated by Django 6.0.6 on 2026-06-24 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Inicio de sesión'), ('register', 'Registro'), ('password_change', 'Cambio de contraseña'), ('admin_action', 'Acción administrativa')], max_length=30, verbose_name='acción')),
                ('detail', models.TextField(blank=True, verbose_name='detalle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'db_table': 'accounts_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar_url', models.URLField(blank=True, max_length=500, verbose_name='avatar')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='dirección')),
                ('emergency_contact', models.CharField(blank=True, max_length=200, verbose_name='contacto de emergencia')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono de emergencia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
                'db_table': 'accounts_profile',
            },
        ),
    ]
