# Generated by Django 6.0.6 on 2026-07-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auditlog_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitud'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitud'),
        ),
    ]
