# Generated by Django 6.0.6 on 2026-06-28 13:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_busstop_is_active_alter_route_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='código')),
            ],
            options={
                'verbose_name': 'distrito',
                'verbose_name_plural': 'distritos',
                'db_table': 'transport_district',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransportCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('tax_id', models.CharField(max_length=20, unique=True, verbose_name='ruc')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='dirección')),
            ],
            options={
                'verbose_name': 'empresa de transporte',
                'verbose_name_plural': 'empresas de transporte',
                'db_table': 'transport_company',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'estado de vehículo',
                'verbose_name_plural': 'estados de vehículo',
                'db_table': 'transport_vehicle_status',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'tipo de vehículo',
                'verbose_name_plural': 'tipos de vehículo',
                'db_table': 'transport_vehicle_type',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='busstop',
            options={'ordering': ['-created_at'], 'verbose_name': 'parada', 'verbose_name_plural': 'paradas'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['-created_at'], 'verbose_name': 'ruta', 'verbose_name_plural': 'rutas'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-created_at'], 'verbose_name': 'vehículo', 'verbose_name_plural': 'vehículos'},
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='capacidad'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)], verbose_name='año'),
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sectors', to='transport.district', verbose_name='distrito')),
            ],
            options={
                'verbose_name': 'sector',
                'verbose_name_plural': 'sectores',
                'db_table': 'transport_sector',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='busstop',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bus_stops', to='transport.sector', verbose_name='sector'),
        ),
        migrations.AddField(
            model_name='route',
            name='transport_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='transport.transportcompany', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transport_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='transport.transportcompany', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='transport.vehiclestatus', verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='transport.vehicletype', verbose_name='tipo'),
        ),
    ]
