# Generated by Django 6.0.6 on 2026-06-28 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_district_transportcompany_vehiclestatus_vehicletype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteBusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stop_order', models.PositiveIntegerField(verbose_name='orden')),
                ('estimated_minutes_from_start', models.PositiveIntegerField(blank=True, null=True, verbose_name='minutos estimados desde inicio')),
                ('bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_routes', to='transport.busstop', verbose_name='parada')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='transport.route', verbose_name='ruta')),
            ],
            options={
                'verbose_name': 'parada de ruta',
                'verbose_name_plural': 'paradas de ruta',
                'db_table': 'transport_route_bus_stop',
                'ordering': ['stop_order'],
            },
        ),
        migrations.AddField(
            model_name='route',
            name='bus_stops',
            field=models.ManyToManyField(related_name='routes', through='transport.RouteBusStop', through_fields=('route', 'bus_stop'), to='transport.busstop', verbose_name='paradas'),
        ),
        migrations.AddConstraint(
            model_name='routebusstop',
            constraint=models.UniqueConstraint(fields=('route', 'stop_order'), name='uq_route_stop_order'),
        ),
        migrations.AddConstraint(
            model_name='routebusstop',
            constraint=models.UniqueConstraint(fields=('route', 'bus_stop'), name='uq_route_bus_stop'),
        ),
    ]
