# Generated by Django 6.0.6 on 2026-06-28 13:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0003_district_transportcompany_vehiclestatus_vehicletype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('license_number', models.CharField(max_length=30, unique=True, verbose_name='licencia')),
                ('license_type', models.CharField(choices=[('A', 'Tipo A (Automóvil)'), ('B', 'Tipo B (Camioneta)'), ('C', 'Tipo C (Bus)'), ('D', 'Tipo D (Camión)'), ('E', 'Tipo E (Pesado)')], default='C', max_length=1, verbose_name='tipo de licencia')),
                ('hire_date', models.DateField(verbose_name='fecha de contratación')),
                ('experience_years', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='años de experiencia')),
                ('observations', models.TextField(blank=True, verbose_name='observaciones')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponible')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'conductor',
                'verbose_name_plural': 'conductores',
                'db_table': 'operations_driver',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Preventivo'), ('corrective', 'Correctivo'), ('predictive', 'Predictivo'), ('emergency', 'Emergencia')], default='preventive', max_length=20, verbose_name='tipo de mantenimiento')),
                ('description', models.TextField(verbose_name='descripción')),
                ('scheduled_date', models.DateField(verbose_name='fecha programada')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='fecha de realización')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='costo')),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='scheduled', max_length=20, verbose_name='estado')),
                ('observations', models.TextField(blank=True, verbose_name='observaciones')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenances', to='transport.vehicle', verbose_name='vehículo')),
            ],
            options={
                'verbose_name': 'mantenimiento',
                'verbose_name_plural': 'mantenimientos',
                'db_table': 'operations_maintenance',
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('departure_time', models.TimeField(verbose_name='hora de salida')),
                ('arrival_time', models.TimeField(verbose_name='hora de llegada')),
                ('frequency_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='frecuencia (minutos)')),
                ('operating_days', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^[1-7]+$', 'Use dígitos 1-7 donde 1=Lunes, 7=Domingo')], verbose_name='días de operación')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='transport.route', verbose_name='ruta')),
            ],
            options={
                'verbose_name': 'horario',
                'verbose_name_plural': 'horarios',
                'db_table': 'operations_schedule',
                'ordering': ['route', 'departure_time'],
            },
        ),
        migrations.CreateModel(
            name='DriverAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assignment_date', models.DateField(verbose_name='fecha de asignación')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fecha de fin')),
                ('is_active_assignment', models.BooleanField(default=True, verbose_name='asignación activa')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='operations.driver', verbose_name='conductor')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='transport.vehicle', verbose_name='vehículo')),
            ],
            options={
                'verbose_name': 'asignación de conductor',
                'verbose_name_plural': 'asignaciones de conductores',
                'db_table': 'operations_driver_assignment',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_active_assignment', True)), fields=('vehicle',), name='uq_vehicle_active_assignment')],
            },
        ),
        migrations.CreateModel(
            name='RouteCoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('order', models.PositiveIntegerField(verbose_name='orden')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='transport.route', verbose_name='ruta')),
            ],
            options={
                'verbose_name': 'coordenada de ruta',
                'verbose_name_plural': 'coordenadas de ruta',
                'db_table': 'operations_route_coordinate',
                'ordering': ['route', 'order'],
                'constraints': [models.UniqueConstraint(fields=('route', 'order'), name='uq_route_coordinate_order')],
            },
        ),
    ]
