# Generated by Django 6.0.6 on 2026-06-28 13:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('transport', '0004_routebusstop_route_bus_stops_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trip_date', models.DateField(verbose_name='fecha del viaje')),
                ('departure_datetime', models.DateTimeField(verbose_name='salida')),
                ('arrival_datetime', models.DateTimeField(blank=True, null=True, verbose_name='llegada')),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='scheduled', max_length=20, verbose_name='estado')),
                ('passenger_count', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='pasajeros')),
                ('observations', models.TextField(blank=True, verbose_name='observaciones')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='operations.driver', verbose_name='conductor')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='transport.route', verbose_name='ruta')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='operations.schedule', verbose_name='horario')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='transport.vehicle', verbose_name='vehículo')),
            ],
            options={
                'verbose_name': 'viaje',
                'verbose_name_plural': 'viajes',
                'db_table': 'operations_trip',
                'ordering': ['-trip_date', '-departure_datetime'],
            },
        ),
        migrations.CreateModel(
            name='GPSPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='velocidad (km/h)')),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='rumbo (°)')),
                ('recorded_at', models.DateTimeField(verbose_name='fecha/hora del registro')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='operations.trip', verbose_name='viaje')),
            ],
            options={
                'verbose_name': 'posición GPS',
                'verbose_name_plural': 'posiciones GPS',
                'db_table': 'operations_gps_position',
                'ordering': ['trip', 'recorded_at'],
            },
        ),
    ]
