# Generated by Django 6.0.6 on 2026-06-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'tipo de incidente',
                'verbose_name_plural': 'tipos de incidente',
                'db_table': 'incidents_incident_type',
                'ordering': ['-created_at'],
            },
        ),
    ]
