# Generated by Django 6.0.6 on 2026-06-28 14:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        ('operations', '0002_trip_gpsposition'),
        ('transport', '0004_routebusstop_route_bus_stops_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('severity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=10, verbose_name='severidad')),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('in_progress', 'En Progreso'), ('resolved', 'Resuelto')], default='open', max_length=15, verbose_name='estado')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de resolución')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='operations.driver', verbose_name='conductor')),
                ('incident_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='incidents.incidenttype', verbose_name='tipo')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='operations.trip', verbose_name='viaje')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='transport.vehicle', verbose_name='vehículo')),
            ],
            options={
                'verbose_name': 'incidente',
                'verbose_name_plural': 'incidentes',
                'db_table': 'incidents_incident',
                'ordering': ['-created_at'],
            },
        ),
    ]
