# Generated by Django 6.0.6 on 2026-06-28 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('message', models.TextField(verbose_name='mensaje')),
                ('type', models.CharField(choices=[('incident', 'Incidente'), ('system', 'Sistema'), ('warning', 'Advertencia')], default='system', max_length=10, verbose_name='tipo')),
                ('is_read', models.BooleanField(default=False, verbose_name='leído')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_enabled', models.BooleanField(default=True, verbose_name='notificaciones por email')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='notificaciones push')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='notificaciones SMS')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'preferencia de notificación',
                'verbose_name_plural': 'preferencias de notificación',
                'db_table': 'notifications_user_preference',
            },
        ),
    ]
